# Generated by Django 4.1 on 2022-12-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_alter_service_category_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
