# Generated by Django 4.0.1 on 2022-12-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='undefined', max_length=200, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='acc.svg', upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='username', max_length=200, verbose_name='Фамилия клиента'),
        ),
    ]
