# Generated by Django 4.0.1 on 2022-12-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_document'),
        ('service', '0010_service_image'),
    ]

    operations = [
    ]
