# Generated by Django 4.0.1 on 2022-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка салона'),
        ),
    ]
