# Generated by Django 4.1 on 2022-12-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_merge_0010_document_0010_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="categories",
            field=models.ManyToManyField(
                related_name="salons",
                to="service.servicecategory",
                verbose_name="Категории салона",
            ),
        ),
        migrations.AlterField(
            model_name="master",
            name="salon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="masters",
                to="service.salon",
            ),
        ),
    ]
