# Generated by Django 4.0.1 on 2022-12-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_salon_categories_service_image_alter_master_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='undefined', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='username', max_length=200, verbose_name='Фамилия'),
        ),
    ]
