# Generated by Django 4.0.1 on 2022-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_salon_categories_alter_master_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='categories',
            field=models.ManyToManyField(related_name='salons', to='service.ServiceCategory', verbose_name='Категории салона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='undefined', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='username', max_length=200, verbose_name='Фамилия'),
        ),
    ]
