# Generated by Django 4.0.1 on 2022-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_master_salon_master_salon_alter_order_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='salon',
            field=models.ManyToManyField(related_name='masters', to='service.Salon', verbose_name='Салон'),
        ),
    ]
